### ISSUE TITLE
README images aren't loading

### ISSUE THREAD

**Issue by OmgImAlexis** [vasilii-kovalev/hydrate-text#22]
The last two images show this for me. Going to the img src from the README.md I get "badgen error" or the whole page just shows a 500.

<img width="613" alt="Screen Shot 2021-07-04 at 9 01 36 am" src="https://user-images.githubusercontent.com/6525926/124369012-75903900-dca6-11eb-9918-c8651c2d444a.png">

<img width="419" alt="Screen Shot 2021-07-04 at 8 58 39 am" src="https://user-images.githubusercontent.com/6525926/124368999-4aa5e500-dca6-11eb-99a1-e527c264d810.png">

**Comment by vasilii-kovalev** [comment]
Hello.
Yeah, I've also noticed that. In the [next](https://github.com/vasilii-kovalev/hydrate-text/tree/next) branch, I'm going to get rid of them at all.

**Comment by OmgImAlexis** [comment]
Tracking this upstream https://github.com/ngryman/badge-size/issues/94
