### ISSUE TITLE
Improve type checking

### ISSUE THREAD

**Issue by vasilii-kovalev** [vasilii-kovalev/hydrate-text#25]
[generatePath](https://reactrouter.com/web/api/generatePath) function in `React Router` library supports variable names check, comparing ones from the route string and ones from the variables object.
Types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L146-L166

It would be great to implement similar type checking in this library.

I tried to do that myself and found, that the approach above works good in case of fixed `prefix` and `suffix` values. Otherwise, it is hard to handle edge cases like these:
* `prefix` and `suffix` are empty strings (passed explicitly or passed interpolation options object is empty)
* Either `preffix` or `suffix` is passed (the other becomes an empty string by default, see [docs](https://github.com/vasilii-kovalev/hydrate-text#examples) or [implementation](https://github.com/vasilii-kovalev/hydrate-text/blob/main/src/index.ts#L17-L22))
* `prefix` and/or `suffix` are set in `configureHydrateText` and then overridden in the result function:

  ```typescript
  const routeWithCustomInterpolationOptions = "/users/(userId)";

  const hydrateRoute = configureHydrateText({ prefix: ":" });

  // '/users/3'
  console.log(
    hydrateRoute(
      routeWithCustomInterpolationOptions,
      { userId: 3 },
      {
        prefix: "(",
        suffix: ")",
      },
    ),
  );
  ```

Definition of done:
* Functionality haven't suffered
* Type checking has improved
* Linters checks and tests are passing
* Code coverage is 100%

**Comment by ghost** [comment]
It would be great to have some reproducible example on TypeScript Playground, so I can experiment with it and not getting myself into the context (that takes much more time). Promise nothing, but I can try to understand what you want to achieve and find the solution.

**Comment by vasilii-kovalev** [comment]
Created a [playground](https://www.typescriptlang.org/play?#code/PTAEDEHsCdQSwM4IK4FMBcoAWAXHAHBdEAczhy2QCMA6AY0gFtgA3AQwTgBs44BaANaR2XVC2BYAngBNobHKj4KAHjmCIUqBMABMAVgCwAKGMhQAZUjJodDNjyFiwMhWr0mrDt16DhbUeJSsvKKKmpUXJBUwIxscAB2wAg2wMg43Ag0OAjGDPEIOKDQqABKqCQAosr4AMJYbLAAvKDAANoAOu0AegAkNABUANQA-AAUAJQdALoA3gC+AD5TzgDcxrmQ+YXFABIcZZXVdQ2gzQdV+KPF50f10DQIVjao42smRnkFoFp0bPil5Qup1AoxEaGGmAK0ASJHGkJw0PiJFOAD5QDNjKBQJ9ClCYcDzAiYaD-GhQMNhqAAERU17rIxYuAAMxBAEI8UjQAsFqBWbt9oDbg0slocKMObDxujMViiqgcNZ4qAJW8sXN6VjigroEqJTRivguGxbFcAYdancADTUzo9ABktLeczepjAlmstkwuAIRFI5EotAYzHYnB4-CEIjEEhkcgUSlQqmAESiMTiiWSdGAOEk-0y2WM2f+oAAaqTUAAVHOoYESrmgeLIRhUVCwHlUSCQURseIuoyF6ul6FsCJaYFlBjQaQAHgl1tLXDQlf+KN7CQU0CZxurAEl4uv8J35HBNgB5fDpTYIaUM0D4YpMuDKCHKolI1XK5BMh9P+GIkhO+k1xbTdbFAHYYxCcsE0KDEb1GGUsTCX8YUtBDQHYIcRwQZ9BzgYdRAQVCb0ZPcWwPI0L3iM9KOwzBd33Q9KOo498iIrE4RfP8APeICNy3UAak2B8SGsVBwOCBQoNUa8sVGXjyKPU9zxY2jQHosjGJY5jLw48TYwraDuNdCwnk9ewfScFwA3cYMvDDXxI0CCC4zCJNImiWIEiSFIcW7bIshyD5L0KAARCpwAAQQAVQAGXLAB9bcADlywqEoAAUTxiiLy23E8kvik90ty-LzDo0joAUpjlMvYFYKxO9UG-TAqRmKk2I-L9HxauZ2uMZ16RxUAKgAWWKgBNRKUrSzLspKgqivmsq1IqqqtJq-I6plRrmupPqbxQLrlBa-aBveMx3WeL0HF9Zx-TcINPFDHwI38KMgn0+NE2TDy028zMEmkBMAo2LZsGcgzVEwPTIOg4F4JvMIOowvCsLquYOvkzSlJooipUaNF6uxYL0Vve9H2tQ7v1AOZyoYij1po4EsYZnGVLQykidlWUaF50aJqm1KMqynK8oW4qxfMDruaxXmaBZxSqI2wi0LVNDMDCyLYoS5Khdm0X8sKiXSt7LEhuKFAuBwKTCmaE8qAAK1QOgcBoVA92hLQSUwgjxn1VBpGQE00NNS3reg61WniNhGFQa0wVQKZ8cJ1XibB4pzUu0Dmh+P4zQuUYAAMehmHbHzmEvo9jiuZip8vC7pYjZXNwV8GBeJUAAd1AG5Lgzi4s7j6kSEdDUZa1RU5TDm3-cNLdTXNa1CT-EkFxeRvuYxtCkZlRuZQnnUp+QK2badXshryYTRJhyToMwQT4iv3YIZt04ZQV6qaPAaAmAfp+W1RDKUYSN0INFRgRa0H9GYqW-kwXcHdoDgGQPEF2LFk4yWbiTKBbNaqNFTtgpWX8f6MHgS2JBKDKLkmGPg1a2NCEwOIX-OAIlijQFNrKA+SoPqw1UMAiOoCfZaEgbQ1m9CdLvjOsZKoMdDRCNAJ3LALZqz9mxIougAh8QICwFYLg0hQCbm4KDR4ogaCRBIAjLE3Db68LQlSHYqAuCRGtDMZACAWxV1QHMVk+1uYXW0cfPRFAf7d27N8aAP9YAUHkKACg1YUb4VHFEJ2LtQDSEgFoeIAByQoeQcBplAIXVx7iY6oELmheYHVxh43PpeTsqBTGQHMTKKxkMxS2PsY4yAziik6hKV4nxso-E6MCVgYJoBQktgiTE+ohRYmcXxGkjJ2S055ISAUnpHiACMZSm4zFABskpmyWoAClIBYCVCFdJVIaaVOqYNWpJizEWPBhJVpzysR2IcU4-Zbjemx28dLFobp-G6OmWMiZ4SYDTOiXM2siyEBZJyZsVZSpCm-K2Ts7meyDmxyOdSU55zQCXNQNcreuyyXsTue8T4dSGlNJvC0m27zqQdO+Ti1AAK0JDICWCyAISlSTKhVE2Zij5mcnhYilZ+S0XFNxZi2U2L0WHJOWci5VybnlNTmXY6e1AUUtAFU4we8gr5FpU85pL9oLMs+Z0607LOVN25aCoJfLxkCshZEmZ0zqxwvSQi5ZuTpXsu2eUn5srUB4qpAStVJKNW7NTnXHVNI9W3KNTU01jzGnPMZVa9pXyulhr+RygZWInUjPBe6qZwrvViuRBKgNyKg1KrlaG4NKrCXEtJYCrmsptUnUBViRN-a0L6sNUYY1NLM30ssZamxTcqSpF+dodAPTtzSBLUCiwILy2uohVWr1sLXx1r9ZKwNayZXQDXSG3Zhar2YE2XGrFWryZJvQBu0dVKjFmqzRa15TLbGLpbMu1d67AVlt5fysJ+6YWiviWjJJztCj1qRXuJtLY13yqxBUzVTcGovpam+lNu9P0muMfU81DLZ1tPnT0hAG7wMusg4Kz1MGfVHtSSehtqHz3IELtaQuCA+MFNKfx6AQmBOYfRPqrDz6mrdV1SO1N4701kbpdmqj1raP0eBcMiDbqoNCoPaK31SyUMovWeJwT-GRMFLE-xwT5TpMYO5kOhTTcP1pvuRm8jP7KN-tzTRpd2mt26cY-p5j0KRVsb-Bx0zUqeOWfEzZwudmCkOfJd22Tu1k0Js-Nl99SmJ0PJ89Ol5+l-2BaA8F8w269N7sM6x2tsX-VmaDYl6z4nUsScc92jzymvNfBaSUKwChgSX2YdfDTey+3UjfTTIr3m1O-v0sNtIqBrWAegNoUYIHxjVdq2F+rLGotNeQ-F1FIHr1YtvdIPFABmR9CqsvyapKMDdg68svb20Rm8Y7G5AA) with a bunch of cases of type checking that should fail with improved types.

**Comment by ghaiklor** [comment]
Thanks for a detailed playground, it is really helpful!

I had a quick look and from what I understood, you need to create a "parser" on type-level that operates on string type literals. For that, you can inspect into [template literal types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types).

Unfortunately, I can't say that it is ezpz work. It is a huge epic, but it is doable. Here, for example, a simple parser to extract the name inside the curly block:

```typescript
type ParseCurlyBlock<T> = T extends `{${infer N}}` ? N : never
type R = ParseCurlyBlock<'{username}'> // R = "username"
```

Afterwards, you can combine these parsers together with recursive types to get a list of all variables inside your template and collect it as a union of possible variables that reflects the state of "what variables can I pass in".

One drawback that I already see is that you can't configure them in runtime as you do with `prefix` or `suffix`, because you need to know what is the prefix and suffix at compile time. You can overcome that with constant values and it seems like it will work.

I will have some spare time at these weekends and could take a closer look and implement some basic implementation of typed templates. I hope this implementation will give you some insights on how to go further with it. Until then, please, make yourself comfortable with template literal types because you really need this in order to achieve what you want (unless I misunderstood something).

**Comment by vasilii-kovalev** [comment]
Thank you! I'm aware of the template literal types, and they are used in `generatePath` type definition (see the very beginning of this issue's message). The problem is in the "dynamic" nature of the markers (`prefix`/`suffix`).

**Comment by ghaiklor** [comment]
Unless you don't parametrize the type to hold prefix and suffix type literals 😉 

```typescript
type Parser<P extends string, S extends string, I> = I extends `${P}${infer N}${S}` ? N : never

type R0 = Parser<"{", "}", "{username}">
type R1 = Parser<"(", ")", "(username)">
```

What is blocking you from specifying your prefix and suffix as type parameters and Typescript will infer automatically from usage? 🙂

**Comment by ghaiklor** [comment]
JFYI, I've already solved the task, but I'm wondering if you got the idea and did it yourself 😉 
I'll post a solution tomorrow on my Telegram channel with step-by-step explanation. It is a good one task indeed.

**Comment by vasilii-kovalev** [comment]
@ghaiklor, yes, I did basically the same, but there are problems with the edge cases I mentioned in this issue' message.
I'll try to create my implementation in an hour and share it here.

**Comment by vasilii-kovalev** [comment]
That's my best try at the moment. It works for very simple cases, but fails in a little more complex ones (especially, with `prefix`/`suffix` as empty strings).

```typescript
type ValueType = string | number | boolean;

type Variables = Record<string, ValueType>;

interface InterpolationOptions<Prefix extends string = string, Suffix extends string = string> {
  prefix?: Prefix;
  suffix?: Suffix;
}

type GetVariables<
  Text extends string,
  Prefix extends string,
  Suffix extends string
> = string extends Text
  ? { [variable in string]?: ValueType }
  : Text extends `${infer _Start}${Prefix}${infer Variable}${Suffix}${infer Rest}`
    ? { [variable in Variable]: ValueType } & GetVariables<Rest, Prefix, Suffix>
    : {};

interface HydrateText {
  <
    Text extends string = string,
    Prefix extends string = "{",
    Suffix extends string = "}",
  >(
    text: Text,
    variables?: GetVariables<Text, Prefix, Suffix>,
    interpolationOptions?: InterpolationOptions<Prefix, Suffix>,
  ): string;
}

interface ConfigureHydrateText {
  <
    _Prefix extends string = "{",
    _Suffix extends string = "}"
  >(interpolationOptions?: InterpolationOptions<_Prefix, _Suffix>): <
    Text extends string = string,
    Suffix extends string = _Suffix,
    Prefix extends string = _Prefix,
  >(
    text: Text,
    variables?: GetVariables<Text, Prefix, Suffix>,
    interpolationOptions?: InterpolationOptions<Prefix, Suffix>,
  ) => string;
}

const DEFAULT_INTERPOLATION_OPTIONS: InterpolationOptions<"{", "}"> = {
  prefix: "{",
  suffix: "}",
};

const EMPTY_INTERPOLATION_OPTIONS: InterpolationOptions<"", ""> = {
  prefix: "",
  suffix: "",
};

const hydrateText: HydrateText = (
  text,
  variables,
  interpolationOptions,
) => {
  const { prefix, suffix } = interpolationOptions
    ? {
        ...EMPTY_INTERPOLATION_OPTIONS,
        ...interpolationOptions,
      }
    : DEFAULT_INTERPOLATION_OPTIONS;

  const resultText = Object.entries(variables ?? {}).reduce(
    (resultText, [name, value]) => {
      const regExpSource = escapeRegExp(`${prefix}${name}${suffix}`);
      const regExp = new RegExp(regExpSource, "g");

      return resultText.replace(regExp, String(value));
    },
    text as string,
  );

  return resultText;
};

const configureHydrateText: ConfigureHydrateText =
  interpolationOptionsFromConfigurer =>
  (text, variables, interpolationOptionsFromInnerFunction) => {
    const interpolationOptions =
      interpolationOptionsFromInnerFunction ??
      interpolationOptionsFromConfigurer;

    /*
      `interpolationOptions` throws an error:
      Argument of type 'InterpolationOptions<_Prefix, _Suffix> | InterpolationOptions<Prefix, Suffix> | undefined'
      is not assignable to parameter of type 'InterpolationOptions<Prefix, Suffix> | undefined'.
    */
    return hydrateText(text, variables, interpolationOptions);
  };
```

[Playground](https://www.typescriptlang.org/play?#code/PTAEDEHsCdQSwM4IK4FMBcoAWAXHAHBdEAczhy2QCMA6AY0gFtgA3AQwTgBs44BaANaR2XVC2BYAngBNobHKj4KAHjmCIUqBMABMAVgCwAKGMhQAZUjJodDNjyFiwMhWr0mrDt16DhbUeJSsvKKKmpUXJBUwIxscAB2wAg2wMg43Ag0OAjGDPEIOKDQqABKqCQAosr4AMJYbLAAvKDAANoAOu0AegAkNABUANQA-AAUAJQdALoA3gC+AD5TzgDcxrmQ+YXFABIcZZXVdQ2gzQdV+KPF50f10DQIVjao42smRnkFoFp0bPil5Qup1AoxEaGGmAK0ASJHGkJw0PiJFOAD5QDNjKBQJ9ClCYcDzAiYaD-GhQMNhqAAERU17rIxYuAAMxBAEI8UjQAsFqBWbt9oDbg0slocKMObDxujMViiqgcNZ4qAJW8sXN6VjigroEqJTRivguGxbFcAYdancADTUzo9ABktLeczepjAlmstkwuAIRFI5EotAYzHYnB4-CEIjEEhkcgUSlQqmAESiMTiiWSdGAOEk-0y2WM2f+oAAaqTUAAVHOoYESrmgeLIRhUVCwHlUSCQURseIuoyF6ul6FsCJaYFlBjQaQAHgl1tLXDQlf+KN7CQU0CZxurAEl4uv8J35HBNgB5fDpTYIKcABWKTLgym+qlQ8WkCGVRM5zVnFmQTPvj4Jgor7vrW36fiQaIYgyoD4HeD4QqAt6oABqrKn+AGIeYGEPk69L9qAADi8qDnAw6iFeMrlkBT7AW+H6IiQloyshAG0S+9GzjK2H-g+7EgQxMLGGi4GMfx9HUaoMqUjMoCtOwQ4jvAuoQVMiHzouVagOqMGYJJhRARx74AAY9DMCRMi2oAAPqEg0OBzGZrEPo55nxJZsCkeRqCuTxAGuRZVllAUczGTKWIyXJClkUpCQlg0MWiFMmAaRWWlzKAdpESRCXeVewU4NaznKNafkPii4WgJg8yrnuLabrYoA7DGIT6dKMFTpVbWGQJYGCUizEwVixXiaBEHAlSMxUoNsq-rxgHPr143NFSczTTKKKjJVYR6UBM2ytFeWIcROBeSOV76UV8ElXNAEovtjJ1dAB5Ghe8Rnm9CCIbu+6Hm9H3HvkN7XaVOHKPdMpwv1JB4e8a71VuoA1Js94kNYqDNcEChtdBWKdUNNkjT1nHLdSU0PTZZULXRY1iSta0baM8PPX9gMA5e31PS9R6nuegNXtZxXWrZYMolD+Ozd1i0k3T0MU1To3Q8CIvzRTRPS7T+LNILIOM9tQG7aoFOHedx05YpFFTpdSEg7d5UU8z3P-XzHOYD9LZO2zLtA0Ldvg-tUqNGiKrGDproWE8nr2D6TguAG7jBl4Ya+JGgQtXGYRJpE0SxAkSQpDi3bZFkOQfJehQACIVOAACCACqAAy5bWduABy5YVCU14ng3NfltuJ6t9ZJ7Xv3g-mG7XOs7zn1TpN03UmtIntVicEoQ+mDz-tKDzZva2Dc69I4qAFQALKjwAmi37ed93vdj0PI8PxPoDuyzr1e7PNLWjSy+47B11N7rRgjvACQCD69jMO6Z4XoHC+mcP6NwQZPChh8BGfwUYgixlCEBLOKZc7phSAkaQCYS4bC2NgdOFYDZNSoW1ZoW0YJhH2ibCi+1HbT3et7BAg1A5QRlMfWSa8ALWlAXxDKzQOEfxnvzSqMlKqzRoEos+l9r4dy7j3PuA9H6j20eYCmiilFSJ5lwz6BjtKVUwFXWujdm5t3UXfLRg9h66PHr2LEx9igoC4DgehoATxUAAFaoDoDgGgL4iRaBJBbUcFJ0RzHGPqVA0hkAmkqqabxvi9pyXiGwRgqBrRglQFMPhK9ZrYnLnKc00DGrNB+H8M0FxRimRmMIlyZlcn5NcmI5QoU6QEw8ZU4o5pgTxFQAAd1ADcS4wyLg1IKdSEgjoNTlK1IqOUmT9JJMNFuU05pSoQRJAuF4-TZpzApmEUAHA5aQ3cXKbUSovHIB8fpJ0vZj55FRujTG2D9KYGRu5OAaNdh0Joo0GUxjnafXANAJgAKvnFCaBVGCoxmGgFYVoa0kLP78xhUwXcYzoDgGQPEUJgNSn-0GRQ7FMjLynAUcpX60jTG4thYwAlLZiWkreuSYYDKaUssvHixg8KgXo2gHczU8p1lYNakBVF2SMU8MZR7Th7N8inO0pAsAVQ8mGkxaAcZWAWzVgInQY1dABD4gQFgKwXBpCgE3NwchjxRA0EiCQRhWJZXY3lZVKkOxUBcEiNaGYyAEAtk6T5VkwDZpQNtc8h1FBYWTO7N8aAsLYAUHkKACg1YlWgCiME0JoBpCQC0PEAA5IUPIOA0ygGMuGyNeTUBhQJvMAOvD3mXk7Kgd1kBPUyh9dQ1QXrZQBqDSG9ETadQtrmDGim8a7VJqwCmq5SoWyZtzfUQoealZlordWipe562NojbO-JABGNts1ZIzqjZezeAApSAWAlQV3LVSbSnbjD9Jdb2-tg6YLDv0mOrEE7g2QGtPeltC7KpLsTdutdabN0wG3TmvdtYD0ICrTWzYda4pnubVem9so73nofc+1977P3fsqh2yGXaj49rdR6sdIG-UEwg1OmD+S4MEwQ-apDkBU0bozWh7Nu7jX7vLTho9tbT28dQNe+joAlOPupC+t9oAP2oC-ec+jDK2nKHAZVAzMFxhMfeJ8ADbGh2gtHf6wNkHoMUdg7G2UgmV3IbE1uyT27qxYdk7h49BGlREYvcp0jWJyPEeU1R7Tun9MU0pbKHppmCbmaxJZ393b8i2YHexhzYonOTqg2ptzfGPNYi88J0T6a-M7oCzJw9eGT2EfU9F9EFW4saapFpmjem6PtqM4A6k1W0tgwy2cn9Rg-1l3y6xwr9msYjpK1x1I57tDoBnduaQE3avJpE+uhrEmmuYfGthkLCmOvnr2yp9tPXoD3cwJe4bt7RvrxM9SdAE2sugBy3NvLrq+12eA8VsD1JNstm27t-bi63QJqE0d+rqGs3nekwWotITChXfk-hxTd3pBdYYyNgZACvub1+xTf7gP5s2aW0B71EP-UzoQAdxHy66snbR+hqTgXLvBfx+18LyBjLWmMggcXDbW0S+gNLyXJP-sxc+2A8bNPZv05Y6D5b4PVugdZ1tjnFgkfeeOyh8T6OMPSaC610LimFdS4l7Lht8uJdS-o8rsps10vq7M5r4HBWmeUP15x2aVI2fG-MKb7nFvGvW4F2JPHbWwsNrF+7hXLvjJu4bR79tXvUurzG9-BlvuS+ZYD8xxbOvg8ccc1xyPCOTdc5Rzzy3fPmu27kynh3GfncK5z4rz3KXadWZdYUYdJQrAKGBJ8sVILQ+jqEcX372ktfV8A0V1bU+0ioEh1SaH0BtCjDh+MKPMfW9x7Ownlr3f7e3ZbPdknT2XugAAMzvbI6rje1JRgTaxGXmfhroxrlsYEAA).

**Comment by ghaiklor** [comment]
> prefix and suffix are empty strings (passed explicitly or passed interpolation options object is empty)

These cases need to be handled explicitly via `P extends "" ? <P is empty> : <P is not empty>`.

> Either preffix or suffix is passed (the other becomes an empty string by default, see docs or implementation)

Why an empty string? But, anyway, if so, see ☝🏻 I'd make some char by default, not the empty string.

> prefix and/or suffix are set in configureHydrateText and then overridden in the result function:

You can try to pack the P and S types in resulting function from `configureHydrateText` and override them later via type parameters.

**Comment by ghaiklor** [comment]
[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgJwM4QGqIJZwEYBsJIA8AUFGbFBAB7AQB2AJklEsAhnQOYA0p5AypRr0mLNhx58yASWIA+KAF4o0obUbMABgBIA3hwBmEBFAASAXz0xL+ukZMA5G-xuHjUACrnNUAPxQHKAAfWEQUdHYcfCIYbih+OI8FAC4oOggAN2NiYgYIAGNcRGgDAFc6fOAMAHs6KAALEAYEOFoScgpqdVFWdi5eDsEukWZeiQHyDzURsT7OeQAKKShaGlSPCbIMzCiCVIAlAuqEBkJ4ZDQdvAIzuITPOTjygGs6aoB3Okfl6rAq2qQqV0UDACAgBgwVFSsRYpQMEKh8Sg5mIAEpUmMuDl8gDgFB9gAGJQNJotWgLADkpgguFw1TiulKKAQdDgAFsIOYKQyoEzjKyOakKQABTj1OAYZ50hAU5E80HgyFC3Tc2HwpVQClc5Go4g4uisfEARmJjWarQglOptPpUEZzIFnKgcEYdpd1WA9WMXJ5fJZ7IgQtF4sl0tV7s9xiFjtl5nlYIRytVSDhic12vMuv1hv2ACZTaSLZSAMJM4DVNlQABECoRVedrqrKfVVCrquBtY1FOTqa7sfjisRFLbcWbaeHsdRQA)
