### ISSUE TITLE
issue when the testrunner is jest

### ISSUE THREAD

**Issue by sarahBuisson** [vasilii-kovalev/hydrate-text#33]
Hello, I use your lib and I have an issue when I test it with jest:
I have this error :
Cannot use exports statement outside a module

on the last line of your dist/index.js :

`exports = { configureHydrateText, hydrateText };
`

I can correct it if I replace it by:
`module.exports = { configureHydrateText, hydrateText };
`

I'm not sure if the issue is in my Jest config or in your build. I don't have the issue when I launch my app, only during the jest test.

**Comment by vasilii-kovalev** [comment]
Hello, @sarahBuisson!
Does the approach described [in this comment](https://github.com/vasilii-kovalev/hydrate-text/issues/32#issuecomment-888914548) solve the problem?

**Comment by vasilii-kovalev** [comment]
Since there were no response for a long time, I'm closing the issue. If the problem still persists, please, add a comment to the issue #32.
